require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'AmbiNext' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  use_flipper!('Flipper' => '0.81.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')

  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  # accomanying npm package: "react-native-flex-debugging": "https://github.com/ShotSkydiver/react-native-flex-debugging#0.1.9",
  # pod 'FLEX', :configurations => ['Debug']

  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'RichChatNotification' do
  pod 'Firebase/Messaging'
end
